chore(hub): move the package into the service package
RSS3-Network/Global-Indexer pull request #134
Opened 2024-03-26 11:34 UTC by kallydev

2024-04-01 19:12 UTC, HenryQW requested changes
Since viper is being introduced here, it should replace `internal/config/config.go`.

2024-04-08 12:48 UTC, HenryQW submitted a review, later dismissed

2024-04-09 22:48 UTC, HenryQW approved these changes

2024-04-10 02:08 UTC, kallydev commented on cmd/main.go
> +
Only test environments need to use these flags. NaturalSelectionLabs/DSL-Global-Indexer-Deploy#14

2024-04-10 02:10 UTC, merged