feat: add Special Rewards calculation and test
RSS3-Network/Global-Indexer pull request #151
Opened 2024-03-31 23:58 UTC by HenryQW

2024-04-02 12:11 UTC, kallydev requested changes

2024-04-02 12:11 UTC, kallydev commented on internal/service/settler/settler.go
> +			fmt.Errorf("failed to parse staking pool tokens: %s", node.StakingPoolTokens)
Unused error.

2024-04-02 12:11 UTC, kallydev commented on internal/service/settler/settler.go
> +			fmt.Errorf("failed to parse staking pool tokens: %s", node.StakingPoolTokens)
Unused error.

2024-04-03 05:03 UTC, polebug commented on internal/service/settler/settler.go
> +	return nil
I am confused, why does it return nil?

2024-04-03 06:35 UTC, polebug commented on internal/service/settler/server.go
> +	stakingContract, err := l2.NewStaking(contractAddresses.AddressStakingProxy, ethereumClient)
`ethereumClient` and `stakingContract` are duplicates

2024-04-03 06:41 UTC, polebug commented on internal/service/settler/settler.go
> +			node.StakingPoolTokens = stakePoolTokens.String()
There should be a need to maintain 18 precision, I think

2024-04-03 06:46 UTC, polebug commented on internal/service/settler/settler.go
> +			stakePoolTokens.Div(stakePoolTokens, tokenDecimals)
It's better to keep 18 decimals here I think, because it is handled this way elsewhere as well

2024-04-03 06:56 UTC, polebug submitted a review, later dismissed

2024-04-04 05:38 UTC, pseudoyu approved these changes

2024-04-04 05:49 UTC, polebug approved these changes

2024-04-04 06:03 UTC, merged