feat: change column names
RSS3-Network/Global-Indexer pull request #207
Opened 2024-04-30 03:15 UTC by Candinya

2024-04-30 04:19 UTC, polebug approved these changes

2024-04-30 17:29 UTC, HenryQW requested changes

2024-04-30 17:29 UTC, HenryQW commented on internal/database/dialer/cockroachdb/table/epoch.go
> +	TotalRewardedNodes    int             `gorm:"column:total_reward_nodes"`
column is not updated

2024-05-02 22:43 UTC, HenryQW commented
please merge #208 first

2024-05-06 13:06 UTC, HenryQW approved these changes

2024-05-06 21:23 UTC, merged