feat(hub): add api to retrieve staker's total value and number of chips
RSS3-Network/Global-Indexer pull request #320
Opened 2024-07-29 12:51 UTC by kallydev

2024-07-30 12:18 UTC, HenryQW requested changes

2024-07-30 12:18 UTC, HenryQW commented on docs/openapi.json
> +                "summary": "Get staker's profile",
Update the summary

2024-07-30 12:18 UTC, HenryQW commented on docs/openapi.json
> +                "description": "Retrieve the total number and value of chips for a specific staker.",
Add "at the time of staking."

2024-07-30 12:18 UTC, HenryQW commented on docs/openapi.json
> +                "description": "A successful response containing a list of chips based on the provided filters. Each chip includes detailed information such as its ID, node address, owner address, an
Update the description

2024-07-30 12:18 UTC, HenryQW commented on docs/openapi.json
> +                                        "total_value": {
Probably use "total_staked_tokens"

2024-07-31 16:34 UTC, HenryQW requested changes

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                "description": "A successful response with the total and current number of staked tokens, as well as the staked number of nodes staked and chips owned by the specific staker.",
> as well as the staked number of nodes staked

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                "description": "A successful response with the total and current number of staked tokens, as well as the staked number of nodes staked and chips owned by the specific staker.",
what does it mean?

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                "description": "Retrieve the total and current number of staked nodes, the number of chips owned, and the amount of tokens for the staker.",
description does not match `StakerResponse`

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                                    "description": "Total cost of chips owned by the staker.",
> Total cost of chips owned by the staker

this is really a confusing description, I suggest: Total number of tokens historically staked (including unstaked tokens).

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                                    "description": "Current number of nodes staked by the staker.",
I'm not sure why it's called "current_staked_nodes", it surely means "total_staked_nodes" right?

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                                "current_owned_chips": {
Same for this, "current_owned_chips" is just "total_chips"

2024-07-31 16:34 UTC, HenryQW commented on docs/openapi.json
> +                                    "description": "Current cost of chips owned by the staker.",
Again this is confusing, do not mix chips with staked tokens. Just use: total amount of tokens currently staked.

2024-07-31 16:34 UTC, HenryQW commented on schema/stake_staker.go
> +	CurrentOwnedChips   uint64          `json:"current_owned_chips"`
use TotalChips, unless we are going to supply a historical count (I don't think so).

2024-08-01 19:15 UTC, HenryQW approved these changes

2024-08-01 19:21 UTC, brucexc approved these changes

2024-08-01 19:22 UTC, merged